// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	Name            string `json:"name"`
	BackgroundImage string `json:"background_image"`
	Icon            string `json:"icon"`
	Description     string `json:"description"`
	JoinDay         int    `json:"join_day"`
	JoinMonth       int    `json:"join_month"`
	JoinYear        int    `json:"join_year"`
	SubscriberCount int    `json:"subscriber_count"`
}

type ChannelSocialMedia struct {
	ID          string `json:"id"`
	ChannelID   string `json:"channel_id"`
	SocialMedia string `json:"social_media"`
	Link        string `json:"link"`
}

type Comment struct {
	ID        string `json:"id"`
	VideoID   string `json:"video_id"`
	ChannelID string `json:"channel_id"`
	Like      int    `json:"like"`
	Dislike   int    `json:"dislike"`
	Content   string `json:"content"`
	Day       int    `json:"day"`
	Month     int    `json:"month"`
	Year      int    `json:"year"`
}

type CommunityPost struct {
	ID        string  `json:"id"`
	ChannelID string  `json:"channel_id"`
	Content   string  `json:"content"`
	Image     *string `json:"image"`
	Like      int     `json:"like"`
	Dislike   int     `json:"dislike"`
	Day       int     `json:"day"`
	Month     int     `json:"month"`
	Year      int     `json:"year"`
}

type Notification struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ChannelID string `json:"channel_id"`
	Content   string `json:"content"`
	IsRead    string `json:"is_read"`
}

type Playlist struct {
	ID               string `json:"id"`
	ChannelID        string `json:"channel_id"`
	Title            string `json:"title"`
	Description      string `json:"description"`
	Privacy          string `json:"privacy"`
	Thumbnail        string `json:"thumbnail"`
	LastUpdatedDay   int    `json:"last_updated_day"`
	LastUpdatedMonth int    `json:"last_updated_month"`
	LastUpdatedYear  int    `json:"last_updated_year"`
	View             int    `json:"view"`
	VideoID          string `json:"video_id"`
}

type PremiumSubscription struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	StartDay   int    `json:"start_day"`
	StartMonth int    `json:"start_month"`
	StartYear  int    `json:"start_year"`
	EndDay     int    `json:"end_day"`
	EndMonth   int    `json:"end_month"`
	EndYear    int    `json:"end_year"`
	Plan       string `json:"plan"`
}

type Reply struct {
	ID        string `json:"id"`
	CommentID string `json:"comment_id"`
	ChannelID string `json:"channel_id"`
	Content   string `json:"content"`
	Day       int    `json:"day"`
	Month     int    `json:"month"`
	Year      int    `json:"year"`
}

type User struct {
	ID              string `json:"id"`
	Email           string `json:"email"`
	RestrictMode    string `json:"restrict_mode"`
	Location        string `json:"location"`
	LikedVideo      string `json:"liked_video"`
	DislikedVideo   string `json:"disliked_video"`
	LikedComment    string `json:"liked_comment"`
	DislikedComment string `json:"disliked_comment"`
	LikedPost       string `json:"liked_post"`
	DislikedPost    string `json:"disliked_post"`
}

type UserSubscription struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	ChannelID      string `json:"channel_id"`
	SubscribeDay   int    `json:"subscribe_day"`
	SubscribeMonth int    `json:"subscribe_month"`
	SubscribeYear  int    `json:"subscribe_year"`
	ShouldNotify   string `json:"should_notify"`
}

type Video struct {
	ID            string `json:"id"`
	ChannelID     string `json:"channel_id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	VideoURL      string `json:"video_url"`
	Thumbnail     string `json:"thumbnail"`
	UploadDay     int    `json:"upload_day"`
	UploadMonth   int    `json:"upload_month"`
	UploadYear    int    `json:"upload_year"`
	Category      string `json:"category"`
	Location      string `json:"location"`
	View          int    `json:"view"`
	Privacy       string `json:"privacy"`
	IsPremium     string `json:"is_premium"`
	AgeRestricted string `json:"age_restricted"`
	Like          int    `json:"like"`
	Dislike       int    `json:"dislike"`
	Duration      int    `json:"duration"`
}

type NewChannel struct {
	UserID          string `json:"user_id"`
	Name            string `json:"name"`
	BackgroundImage string `json:"background_image"`
	Icon            string `json:"icon"`
	Description     string `json:"description"`
	SubscriberCount int    `json:"subscriber_count"`
}

type NewChannelSocialMedia struct {
	ChannelID   string `json:"channel_id"`
	SocialMedia string `json:"social_media"`
	Link        string `json:"link"`
}

type NewComment struct {
	VideoID   string `json:"video_id"`
	ChannelID string `json:"channel_id"`
	Content   string `json:"content"`
	Like      int    `json:"like"`
	Dislike   int    `json:"dislike"`
}

type NewCommunityPost struct {
	ChannelID string  `json:"channel_id"`
	Content   string  `json:"content"`
	Image     *string `json:"image"`
	Like      int     `json:"like"`
	Dislike   int     `json:"dislike"`
}

type NewNotification struct {
	UserID    string `json:"user_id"`
	ChannelID string `json:"channel_id"`
	Content   string `json:"content"`
	IsRead    string `json:"is_read"`
}

type NewPlaylist struct {
	ChannelID   string `json:"channel_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Privacy     string `json:"privacy"`
	Thumbnail   string `json:"thumbnail"`
	View        int    `json:"view"`
	VideoID     string `json:"video_id"`
}

type NewPremiumSubscription struct {
	UserID string `json:"user_id"`
	Plan   string `json:"plan"`
}

type NewReply struct {
	CommentID string `json:"comment_id"`
	ChannelID string `json:"channel_id"`
	Content   string `json:"content"`
}

type NewUser struct {
	Email           string `json:"email"`
	RestrictMode    string `json:"restrict_mode"`
	Location        string `json:"location"`
	LikedVideo      string `json:"liked_video"`
	DislikedVideo   string `json:"disliked_video"`
	LikedComment    string `json:"liked_comment"`
	DislikedComment string `json:"disliked_comment"`
	LikedPost       string `json:"liked_post"`
	DislikedPost    string `json:"disliked_post"`
}

type NewUserSubscription struct {
	UserID       string `json:"user_id"`
	ChannelID    string `json:"channel_id"`
	ShouldNotify string `json:"should_notify"`
}

type NewVideo struct {
	ChannelID     string `json:"channel_id"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	VideoURL      string `json:"video_url"`
	Thumbnail     string `json:"thumbnail"`
	Category      string `json:"category"`
	Location      string `json:"location"`
	View          int    `json:"view"`
	Privacy       string `json:"privacy"`
	IsPremium     string `json:"is_premium"`
	AgeRestricted string `json:"age_restricted"`
	Like          int    `json:"like"`
	Dislike       int    `json:"dislike"`
	Duration      int    `json:"duration"`
}
